### ISSUE TITLE
Stop conditions

### ISSUE THREAD

**Issue by Vagab** [diffeo/kodama#13]
Hi. I've been trying to use kodama and it's awesome in everything so far, thank you for this great library.

One thing I would love to see is something like stop conditions. To elaborate, here's an [example](https://docs.rs/linfa-hierarchical/latest/linfa_hierarchical/struct.HierarchicalCluster.html#method.num_clusters) of what [linfa](https://github.com/rust-ml/linfa) does to limit the number of _steps_. Now, my use case might be very contrived but we require a cluster to have a maximum size and that's currently not possible from what I saw.

As a reference, I think scipy allows you to just get a tree and do whatever with it. Not sure if that's something that would work here.

If that feature is something that you agree would be beneficial I can try to write something

**Comment by BurntSushi** [comment]
See: https://github.com/diffeo/kodama/issues/12#issuecomment-2090228505
